from fastapi import FastAPI, Path, HTTPException
from typing import Annotated

app = FastAPI()
users = {'1': 'Имя: Example, возраст: 18'}


@app.get('/users')
async def post_massage() -> dict:
    return users


@app.post('/user/{username}/{age}')
async def poster(username: str, age: int) -> str:
    user_id = str(int(max(users, key=int)) + 1 )
    users[user_id] = f'Имя: {username}, Возраст: {age}'
    return f'User {user_id} is registered'


@app.put("/user/{user_id}/{username}/{age}")
async def mew_user(user_id: int, username: str, age: int) -> str:
    users[user_id] = f'Имя: {username}, Возраст: {age}'
    return f'The user {user_id} is updated'


@app.delete('/user/{user_id}')
async def deleted(user_id: int) -> str:
    if int(user_id) not in users:
        raise HTTPException(status_code=404, detail=f"User {user_id} not found")
    del users[int(user_id)]
    return f"User {user_id} has been deleted"
